### ISSUE TITLE
Where can we download facemesh-lite.f16.tflite ?

### ISSUE THREAD

**Issue by jiapei100** [thepowerfuldeez/facemesh.pytorch#2]
I cannot find **facemesh-lite.f16.tflite** from  [https://github.com/google/mediapipe](https://github.com/google/mediapipe) . Where can we download a facemesh model??

Cheers

**Comment by thepowerfuldeez** [comment]
Hi! I have link to face mesh model in README: https://developers.google.com/ar/develop/ios/augmented-faces/quickstart

**Comment by headupinclouds** [comment]
I don't see any reference to  facemesh-lite.f16.tflite in the quickstart page.  Do you have a direct link?
