### ISSUE TITLE
Full img as input to model?

### ISSUE THREAD

**Issue by zhouhuirun2015** [thepowerfuldeez/facemesh.pytorch#4]
Hi,
    is there a method put full img as input into model and get the right position of detections mapped into ori img?

**Comment by thepowerfuldeez** [comment]
Hello. You can use face detectors, e.g. dlib or https://github.com/ageitgey/face_recognition 
Then you should crop face with offsets and resize.

Hope I helped

**Comment by zhouhuirun2015** [comment]
Thanks for your reply.
